const config = {
  scenes: {
    generic: {
      name: "generic",
      sounds: [
        { name: "typing", sound: ["typing", "typing", "typing"], bus: "ui", type: "roundRobin", },
        { name: "typingDelete", sound: "typingDelete", bus: "ui" },
        { name: "hoverGeneric", sound: "hoverGeneric", bus: "ui" },
        { name: "hoverExpand", sound: "hoverExpand", bus: "ui" },
        { name: "clickGeneric", sound: "clickGeneric", bus: "ui", gain: 0.7},
        { name: "clickEnter", sound: "clickEnter", bus: "ui" },
        { name: "textAppear1", sound: "textAppear", bus: "textBus" },
        { name: "textAppear2", sound: "textAppear", bus: "textBus" },
        { name: "textAppear3", sound: "textAppear", bus: "textBus" },
        { name: "textAppear4", sound: "textAppear", bus: "textBus" },
        {
          name: "textRolling",
          sound: "textRolling",
          bus: "launchScene",
          loop: true,
        },
        { name: "musicMenu", sound: "musicMenu", bus: "master", loop: true, loopEnd: 35.624 },
        { name: "ambMenu", sound: "ambMenu", bus: "master", loop: true },
        { name: "rocketOneshot", sound: "rocketOneshot", gain:0.3, bus: "master" },
        { name: "satelliteOneshot", sound: "satelliteOneshot", bus: "master" },
        { name: "spacejunkOneshot", sound: "spacejunkOneshot", bus: "master" },
        { name: "transmissionOneshot", sound: "transmissionOneshot", bus: "master" },
        {
          name: "hotspotHover",
          sound: ["hotspotHover", "hotspotHover", "hotspotHover"],
          type: "roundRobin",
          gain: 1.4,
          bus: "ui",
        },
      ],
    },
    main: {
      name: "main",
      sounds: [
        { name: "clickMap", sound: "clickMap", bus: "ui" },
        {
          name: "ambLaunchPad1",
          sound: "ambLaunchPad1",
          bus: "mainBus",
          loop: true,
          loopEnd: 4.714,
        },
        {
          name: "rocketDeploy",
          sound: "rocketDeploy",
          bus: "mainBus",
          gain: 0.4221,
        },
        {
          name: "rocketFlight",
          sound: "rocketFlight",
          gain: 0.35,
          bus: "mainBus",
          loop: true,
        },
        { name: "ambSpace", sound: "ambSpace", bus: "mainBus", loop: true },
        {
          name: "rocketLaunch",
          sound: "rocketLaunch",
          bus: "mainBus",
          gain: 0.4221,
        },
        {
          name: "ambLaunchPad2",
          sound: "ambLaunchPad2",
          bus: "mainBus",
          loop: true,
        },
        { name: "ambMap", sound: "ambMap", bus: "map", loop: true },
        { name: "terminalOut", sound: "terminalOut", bus: "ui" },
        { name: "terminalIn", sound: "terminalIn", bus: "ui" },
        {
          name: "guardianNotification",
          sound: "guardianNotification",
          bus: "ui",
        },
        { name: "zoomIn", sound: "zoomIn", bus: "ui", gain: 1.3 },
        { name: "zoomOut", sound: "zoomOut", bus: "ui", gain: 1.3 },
        { name: "ctaClick", sound: "ctaClick", bus: "ui" },

      ],
      bus: "master",
    },
    vo: {
      name: "vo",
      sounds: [
        { name: "launchPadIdle2", sound: "launchPadIdle2" },
        { name: "launchPadIdle8", sound: "launchPadIdle8" },
        { name: "launchPadIdle10", sound: "launchPadIdle10" },
        { name: "launchPadIdle9", sound: "launchPadIdle9" },
        { name: "launchPadIdle6", sound: "launchPadIdle6" },
        { name: "launchPadIdle7", sound: "launchPadIdle7" },
        { name: "launchPad4", sound: "launchPad4" },
        { name: "launchPad5", sound: "launchPad5" },
        { name: "launchPadIdleExtra5", sound: "launchPadIdleExtra5" },
        { name: "launchPadIdleExtra4", sound: "launchPadIdleExtra4" },
        { name: "launchPadIdleExtra3", sound: "launchPadIdleExtra3" },
        { name: "launchPadIdleExtra6", sound: "launchPadIdleExtra6" },
        { name: "launchPad2", sound: "launchPad2" },
        { name: "launchPadIdleExtra10", sound: "launchPadIdleExtra10" },
        { name: "launchPadIdleExtra8", sound: "launchPadIdleExtra8" },
        { name: "launchPadIdleExtra2", sound: "launchPadIdleExtra2" },
        { name: "launchPad1", sound: "launchPad1" },
        { name: "launchPadIdle3", sound: "launchPadIdle3" },
        { name: "launchPadIdle4", sound: "launchPadIdle4" },
        { name: "launchPadIdleExtra7", sound: "launchPadIdleExtra7" },
        { name: "launchSequence7", sound: "launchSequence7" },
        { name: "launchPad3", sound: "launchPad3" },
        { name: "satelliteDeployed4", sound: "satelliteDeployed4" },
        { name: "launchSequence4", sound: "launchSequence4" },
        { name: "launchPadIdle1", sound: "launchPadIdle1" },
        { name: "satelliteDeployed2", sound: "satelliteDeployed2" },
        { name: "launchSequence6", sound: "launchSequence6" },
        { name: "satelliteDeployed1", sound: "satelliteDeployed1" },
        { name: "launchSequence5", sound: "launchSequence5" },
        { name: "launchPadIdleExtra1", sound: "launchPadIdleExtra1" },
        { name: "satelliteDeployed5", sound: "satelliteDeployed5" },
        { name: "satelliteDeployed3", sound: "satelliteDeployed3" },
        { name: "satelliteDeployed6", sound: "satelliteDeployed6" },
        { name: "launchSequence2", sound: "launchSequence2" },
        { name: "launchSequence3", sound: "launchSequence3" },
        { name: "launchPadIdle5", sound: "launchPadIdle5" },
        { name: "launchPadIdleExtra9", sound: "launchPadIdleExtra9" },
        { name: "launchSequence1", sound: "launchSequence1" },
        { name: "clearToLaunchPoll6", sound: "clearToLaunchPoll6" },
        { name: "clearToLaunchPoll4", sound: "clearToLaunchPoll4" },
        { name: "clearToLaunchPoll5", sound: "clearToLaunchPoll5" },
        { name: "clearToLaunchPoll13", sound: "clearToLaunchPoll13" },
        { name: "clearToLaunchPoll7", sound: "clearToLaunchPoll7" },
        { name: "clearToLaunchPoll19", sound: "clearToLaunchPoll19" },
        { name: "clearToLaunchPoll15", sound: "clearToLaunchPoll15" },
        { name: "clearToLaunchPoll9", sound: "clearToLaunchPoll9" },
        { name: "clearToLaunchPoll23", sound: "clearToLaunchPoll23" },
        { name: "clearToLaunchPoll17", sound: "clearToLaunchPoll17" },
        { name: "clearToLaunchPoll21", sound: "clearToLaunchPoll21" },
        { name: "clearToLaunchPoll33", sound: "clearToLaunchPoll33" },
        { name: "clearToLaunchPoll27", sound: "clearToLaunchPoll27" },
        { name: "clearToLaunchPoll31", sound: "clearToLaunchPoll31" },
        { name: "clearToLaunchPoll25", sound: "clearToLaunchPoll25" },
        { name: "clearToLaunchPoll11", sound: "clearToLaunchPoll11" },
        { name: "clearToLaunchPoll2", sound: "clearToLaunchPoll2" },
        { name: "clearToLaunchPoll29", sound: "clearToLaunchPoll29" },
        { name: "clearToLaunchPoll3", sound: "clearToLaunchPoll3" },
        { name: "clearToLaunchPoll1", sound: "clearToLaunchPoll1" },
      ],
      bus: "vo",
    },
  },
  sources: [
    { name: "typingDelete" },
    { name: "typing" },
    { name: "hoverGeneric" },
    { name: "hoverExpand" },
    { name: "clickGeneric" },
    { name: "clickEnter" },
    { name: "clickCard" },
    { name: "clickMap" },
    { name: "textAppear" },
    { name: "textRolling" },
    { name: "ambLaunchPad1" },
    { name: "ambMenu" },
    { name: "rocketDeploy" },
    { name: "rocketFlight" },
    { name: "ambSpace" },
    { name: "musicMenu" },
    { name: "rocketLaunch" },
    { name: "ambLaunchPad2" },
    { name: "ambMap" },
    { name: "terminalOut" },
    { name: "terminalIn" },
    { name: "hotspotHover" },
    { name: "guardianNotification" },
    { name: "zoomIn" },
    { name: "zoomOut" },
    { name: "ctaClick" },
    { name: "launchPadIdle2" },
    { name: "launchPadIdle8" },
    { name: "launchPadIdle10" },
    { name: "launchPadIdle9" },
    { name: "launchPadIdle6" },
    { name: "launchPadIdle7" },
    { name: "launchPad4" },
    { name: "launchPad5" },
    { name: "launchPadIdleExtra5" },
    { name: "launchPadIdleExtra4" },
    { name: "launchPadIdleExtra3" },
    { name: "launchPadIdleExtra6" },
    { name: "launchPad2" },
    { name: "launchPadIdleExtra10" },
    { name: "launchPadIdleExtra8" },
    { name: "launchPadIdleExtra2" },
    { name: "launchPad1" },
    { name: "launchPadIdle3" },
    { name: "launchPadIdle4" },
    { name: "launchPadIdleExtra7" },
    { name: "launchSequence7" },
    { name: "launchPad3" },
    { name: "satelliteDeployed4" },
    { name: "launchSequence4" },
    { name: "launchPadIdle1" },
    { name: "satelliteDeployed2" },
    { name: "launchSequence6" },
    { name: "satelliteDeployed1" },
    { name: "launchSequence5" },
    { name: "launchPadIdleExtra1" },
    { name: "satelliteDeployed5" },
    { name: "satelliteDeployed3" },
    { name: "satelliteDeployed6" },
    { name: "launchSequence2" },
    { name: "launchSequence3" },
    { name: "launchPadIdle5" },
    { name: "launchPadIdleExtra9" },
    { name: "launchSequence1" },
    { name: "mapInRed" },
    { name: "mapInSattelite" },
    { name: "clearToLaunchPoll6" },
    { name: "clearToLaunchPoll4" },
    { name: "clearToLaunchPoll5" },
    { name: "clearToLaunchPoll13" },
    { name: "clearToLaunchPoll7" },
    { name: "clearToLaunchPoll19" },
    { name: "clearToLaunchPoll15" },
    { name: "clearToLaunchPoll9" },
    { name: "clearToLaunchPoll23" },
    { name: "clearToLaunchPoll17" },
    { name: "clearToLaunchPoll21" },
    { name: "clearToLaunchPoll33" },
    { name: "clearToLaunchPoll27" },
    { name: "clearToLaunchPoll31" },
    { name: "clearToLaunchPoll25" },
    { name: "clearToLaunchPoll11" },
    { name: "clearToLaunchPoll2" },
    { name: "clearToLaunchPoll29" },
    { name: "clearToLaunchPoll3" },
    { name: "clearToLaunchPoll1" },
    { name: "mapInSatellite" },
    { name: "rocketOneshot" },
    { name: "satelliteOneshot" },
    { name: "spacejunkOneshot" },
    { name: "transmissionOneshot" },
  ],
  busses: [
    { name: "out", parent: "$OUT", gain: 1 },
    { name: "video", parent: "out", gain: 1 },
    { name: "master", parent: "video", gain: 1 },
    { name: "ui", parent: "master", gain: 0.7879 },
    { name: "launchScene", parent: "master", gain: 1 },
    { name: "map", parent: "launchScene", gain: 1 },
    { name: "vo", parent: "launchScene", gain: 1 },
    { name: "mainBus", parent: "launchScene", gain: 1 },
    { name: "textBus", parent: "ui", gain: 0.5 },
  ],
  basePath: "/audio/",
};
export default config;
